language: c
compiler:
  - clang
  - gcc
before_install:
  - $CC --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq apache2-threaded-dev
  - sudo dpkg-query -L apache2-threaded-dev
  - sudo dpkg -s apache2-threaded-dev | grep 'Version'
script:
  - apxs2 -i -a -c mod_auth_radius.c
