language: c
compiler:
  - clang
  - gcc
before_install:
  - $CC --version
  - sudo apt-get update -qq
  - sudo apt-get --force-yes -fy -q install apache2-dev
  - sudo dpkg -s apache2-dev | grep 'Version'
script:
  - apxs2 -a -c mod_auth_radius.c
