language: c
compiler:
  - clang
  - gcc
before_install:
  - $CC --version
  - sudo apt-get update -qq
  - sudo apt-get -y -qq install apache2 apache2-bin apache2-dev libapr1-dev libaprutil1-dev dh-autoreconf devscripts
  - sudo dpkg-query -L apache2-dev
  - sudo dpkg -s apache2-dev | grep 'Version'
script:
  - sudo apxs2 -Werror -Wall -i -a -c mod_auth_radius.c
  - sudo make deb

